[package]
name = "sysfs-pwm-patterns"
version = "0.1.0"
edition = "2021"

[dependencies]
sysfs-pwm = { git = "https://github.com/otiv-jerome-colle/rust-sysfs-pwm", branch = "feature/pwm-chip-by-name" }
anyhow = "1.0.89"